Using field for location, pagination on past exhibits, features
MITLibraries/MITLibraries-child pull request #131
Opened 2017-06-20 23:46 UTC by hllavina

Using Location field instead of Category for location. this allows featured category to be used to place posts on home page. The display of current, past, upcoming has been changed to display location field rather than the category. The current, past, upcoming views have been condensed into one view, inc/exhibits-detail, the only difference is display of date

2017-06-21 13:26 UTC, frrrances commented
@hllavina can you get the code climate to pass? I'll take a spin through once those changes are up.

2017-06-21 18:07 UTC, hllavina commented
All the code climate issues  have been addressed except for the meta key and meta query issues which are out of scope for these updates. Libraries-dev have been updated with the new changes. thanks for your review

2017-06-21 19:24 UTC, matt-bernhardt commented
I've reviewed the remaining CodeClimate failures and approved them - I agree that it isn't necessary to tackle this issue at the moment.

2017-06-21 21:04 UTC, matt-bernhardt submitted a review, later dismissed
I believe this looks good. Provided it looks good to Frances, I'm comfortable merging this and proceeding into test or production as needed.

2017-06-22 14:34 UTC, frrrances reviewed
One question on the location link, otherwise it looks and acts nicely. I'll let @matt-bernhardt weigh in on any of the WP loops and functions though. Once you address the link, let me know and I'll re-review.

2017-06-22 14:34 UTC, frrrances commented on inc/exhibits-detail.php
> +							<a href="<?php echo esc_url( $cat_link ); ?>"><span class="category-bg"><span class="category-init"><?php echo esc_attr( substr( get_field( 'location' ),0,1 ) ); ?></span></span><span class="c
This link is using cat_link but now the rest is using location. Ideally, this would go to a listing of exhibits for that location, but on dev it is an empty href. Can you take a look and see what's possible to link to here?

2017-06-22 18:44 UTC, hllavina commented on inc/exhibits-detail.php
> +							<a href="<?php echo esc_url( $cat_link ); ?>"><span class="category-bg"><span class="category-init"><?php echo esc_attr( substr( get_field( 'location' ),0,1 ) ); ?></span></span><span class="c
Hi Thanks for the catch, I am fixing. I also noticed that the breadcrumbs are not correct , they should have the location name when displaying a particular location exhibit, should we address this now?

2017-06-22 18:51 UTC, frrrances commented on inc/exhibits-detail.php
> +							<a href="<?php echo esc_url( $cat_link ); ?>"><span class="category-bg"><span class="category-init"><?php echo esc_attr( substr( get_field( 'location' ),0,1 ) ); ?></span></span><span class="c
Good catch! Yes, that would be great.

2017-06-23 13:43 UTC, matt-bernhardt requested changes
The only thing I'd like to see changed would be line 18 on the new detail partial - which looks like it is bound to the exhibits site right now? I believe there are plans to use Exhibits posts in more than just this site, so this seems like something that needs to be site-agnostic.

Everything else looks good.

2017-06-23 13:43 UTC, matt-bernhardt commented on inc/exhibits-detail.php
> +							<a href="/exhibits/<?php echo esc_attr( str_replace( ' ','-',get_field( 'location' ) ) ); ?>"><span class="category-bg"><span class="category-init"><?php echo esc_attr( substr( get_field( 'loc
Is there a way to write this line so it isn't hard-coded to the Exhibits site? Is that available via a Wordpress function in some way?

2017-06-23 19:34 UTC, matt-bernhardt approved these changes

2017-06-23 19:44 UTC, merged